name: Node.js Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.19.1', '20.11.1']

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check if package.json exists
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "package.json"

    - name: Install dependencies
      if: steps.check_files.outputs.files_exists == 'true'
      run: |
        npm install
        npm ci || npm install

    - name: Run tests
      if: steps.check_files.outputs.files_exists == 'true'
      run: npm test || echo "No test script found in package.json" 
